---
- name: master
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    clusterendpoint: https://api.mhjacks-aeg.blueprints.rhecoeng.com:6443
    username: kubeadmin
    password: 'changeme'
  tasks:
    - name: login
      ansible.builtin.shell:
        cmd: oc login --server={{ clusterendpoint }} -u {{ username }} -p {{ password }} --insecure-skip-tls-verify
    - name: clone
      git:
        repo: https://github.com/Enterprise-Neurosystem/edge-anomaly-detection.git
        dest: /home/runner/edge-anomaly-detection
        clone: yes
        update: yes
    - name: Install bottle python package
      ansible.builtin.pip:
        name: bottle
      args:
        chdir: /home/runner/edge-anomaly-detection
    - name: master
      ansible.builtin.shell: 
        executable: python3
        cmd: wsgi.py
      args:
        chdir: /home/runner/edge-anomaly-detection