---
- hosts: localhost
  gather_facts: false
  become: false
  vars:
    clusterendpoint: https://api.mhjacks-aeg.blueprints.rhecoeng.com:6443
    username: kubeadmin
    password: 'changeme'
  tasks:
    - name: login
      ansible.builtin.shell:
        cmd: oc login --server={{ clusterendpoint }} -u {{ username }} -p {{ password }} --insecure-skip-tls-verify


    - name: find
      find:
        paths:
          - /
        recurse: true
        file_type: directory
      register: results
      
    - name: find
      find:
        paths:
          - "{{ item.path }}"
        recurse: true
        file_type: all
        loop: "{{ results }}"
        loop_control:
          label: "{{ item.path }}"
      register: filesFound



    - name: print empty dirs 
      file:
        path: "{{ item.path }}"
      when: >-
         filesFound.matched == 0
      loop: "{{ filesFound }}"
      loop_control:
        label: "{{ item.path }}"

