---
- hosts: localhost
  gather_facts: false
  become: false
  vars:
    clusterendpoint: https://api.mhjacks-aeg.blueprints.rhecoeng.com:6443
    username: kubeadmin
    password: 'changeme'
  tasks:
    - name: login
      ansible.builtin.shell:
        cmd: oc login --server={{ clusterendpoint }} -u {{ username }} -p {{ password }} --insecure-skip-tls-verify

    - name: find
      find:
        paths:
          - /
        recurse: true
        file_type: directory
      register: results

    - name: count files
      find:
        path: "{{ item.path }}"
        register: filesFound
        loop: "{{ results.files }}"
        
    - name: print empty dirs 
      file:
        path: "{{ item.path }}"
      when: >-
         filesFound.matched > 0
      loop: "{{ filesFound.files }}"
      loop_control:
        label: "{{ item.path }}"

