---
- hosts: localhost
  gather_facts: false
  become: false
  vars:
    clusterendpoint: https://api.mhjacks-aeg.blueprints.rhecoeng.com:6443
    username: kubeadmin
    password: 'changeme'
  tasks:
    - name: login
      ansible.builtin.shell:
        cmd: oc login --server={{ clusterendpoint }} -u {{ username }} -p {{ password }} --insecure-skip-tls-verify

    - name: find
      find:
        paths:
          - /HOME
        recurse: true
        file_type: any
      register: results

    - name: not in path
      file:
        path: "{{ item.path }}"
        mode: "u+rwX,go+rX,go-w"
      when: >-
        "/exception" not in item.path
      loop: "{{ results.files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: in path
      file:
        path: "{{ item.path }}"
        mode: "g+w"
      when: >-
        "/exception" in item.path
      loop: "{{ results.files }}"
      loop_control:
        label: "{{ item.path }}"