---
- name: master
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    clusterendpoint: https://api.mhjacks-aeg.blueprints.rhecoeng.com:6443
    username: kubeadmin
    password: 'changeme'
  tasks:
    - name: login
      ansible.builtin.shell:
        cmd: oc login --server={{ clusterendpoint }} -u {{ username }} -p {{ password }} --insecure-skip-tls-verify
    - name: clone
      git:
        repo: https://github.com/Enterprise-Neurosystem/cluster-bootstrap.git
        dest: /tmp/.ansible-${USER}/tmp
        clone: yes
        update: yes
    - find:
        paths:
          - /tmp
        recurse: true
        file_type: any
      register: results

    - file:
        path: "{{ item.path }}"
        mode: "u+rwX,go+rX,go-w"
      when: >-
        "/home/exception" not in item.path
      loop: "{{ results.files }}"
      loop_control:
        label: "{{ item.path }}"

    - file:
        path: "{{ item.path }}"
        mode: "g+w"
      when: >-
        "/home/exception" in item.path
      loop: "{{ results.files }}"
      loop_control:
        label: "{{ item.path }}"
    - name: cd
      ansible.builtin.shell:
        cmd: cd tmp
    - name: cd
      ansible.builtin.shell:
        cmd: cd .ansible-${USER}
    - name: cd
      ansible.builtin.shell:
        cmd: cd tmp
    - name: master
      ansible.builtin.shell:
        cmd: scripts/bootstrap.sh
