---
- name: master
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    clusterendpoint: https://api.mhjacks-aeg.blueprints.rhecoeng.com:6443
    username: kubeadmin
    password: 'changeme'
  tasks:
    - name: login
      ansible.builtin.shell:
        cmd: oc login --server={{ clusterendpoint }} -u {{ username }} -p {{ password }} --insecure-skip-tls-verify

    - name: clone
      git:
        repo: https://github.com/Enterprise-Neurosystem/cluster-bootstrap.git
        dest: /output/stdin
        clone: yes
        update: yes
        force: yes
    - name: debugging
      debug: 
        msg: "{{ lookup('env', 'output/stdin') }}"
    - name: debugging
      debug: 
        msg: "{{ lookup('env', 'usr/tmp') }}"
    - name: master
      ansible.builtin.shell:
        cmd: cd usr/tmp
    - name: master
      ansible.builtin.shell:
        cmd: cd cluster-bootstrap
    - name: master
      ansible.builtin.shell:
        cmd: cd scripts
